[auth]
redirect_uri = "https://ai-skill-gap-analyzer-8ax36dxpjuxbdzewm6ejmv.streamlit.app/oauth2callback"
cookie_secret = "TITHI_ROUT_I_WILL_MARRY_YOU"

[auth.google]
client_id = "865131387261-jvum9kf9jo0tsuiihvl8f4604gasfnq4.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
